defmodule Red.Repo.Migrations.AddFieldsToUser do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :email_verified, :boolean
      add :picture, :text
      add :name, :text
    end
  end

  def down do
    alter table(:users) do
      remove :name
      remove :picture
      remove :email_verified
    end
  end
end