defmodule Red.Repo.Migrations.AddAuth0IdToUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :auth0_id, :text
    end

    create unique_index(:users, [:auth0_id], name: "users_unique_auth0_id_index")
  end

  def down do
    drop_if_exists unique_index(:users, [:auth0_id], name: "users_unique_auth0_id_index")

    alter table(:users) do
      remove :auth0_id
    end
  end
end
