defmodule Red.Repo.Migrations.AddPhraseToCard do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:cards) do
      add :phrase, :text, null: false
    end
  end

  def down do
    alter table(:cards) do
      remove :phrase
    end
  end
end