name: Bump Elixir

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  bump-elixir:
    name: Bump Elixir
    uses: dewetblomerus/actions-elixir/.github/workflows/bump-elixir.yml@main
    secrets:
      create-pull-request-token: ${{ secrets.CREATE_PULL_REQUEST_TOKEN }}
