name: Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  mix-check:
    uses: dewetblomerus/actions-elixir/.github/workflows/elixir-ci.yml@main
